[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter web build"]

[start]
cmd = "pnpm start"
